enum Preposition: String {
    
    case behem = "během"
    case bez = "bez"
    case beze = "beze"
    case blizko = "blízko"
    
    case cestou = "cestou"

    case dik = "dík"
    case diky = "díky"
    case dle = "dle"
    case dox = "do"
    
    case jmenem = "jménem"
    
    case k = "k"
    case ke = "ke"
    case kol = "kol"
    case kolem = "kolem"
    case krom = "krom"
    case krome = "kromě"
    case ku = "ku"
    case kvuli = "kvůli"
    
    case mezi = "mezi"
    case mimo = "mimo"
    case místo = "místo"
    
    case na = "na"
    case nad = "nad"
    case nade = "nade"
    case namisto = "namísto"
    case napric = "napříč"
    case naproti = "naproti"
    case navrch = "navrch"
    case navzdory = "navzdory"
    case nedaleko = "nedaleko"
    case nevyjimaje = "nevyjímaje"
    
    case o = "o"
    case ob = "ob"
    case od = "od"
    case ode = "ode"
    case ohledne = "ohledně"
    case okolo = "okolo"
    case oproti = "oproti"
    
    case po = "po"
    case pobliz = "poblíž"
    case pod = "pod"
    case pode = "pode"
    case podel = "podél"
    case podle = "podle"
    case podleva = "podlevá"
    case podliva = "podlivá"
    case pmoci = "pomocí"
    case pred = "před"
    case prede = "přede"
    case pres = "přes"
    case prese = "přese"
    case pri = "při"
    case pro = "pro"
    case prostrednictvim = "prostřednictvím"
    case proti = "proti"
    
    case s = "s"
    case se = "se"
    case skrz = "skrz"
    case skrze = "skrze"
    case stran = "stran"
    case stranou = "stranou"
    
    case u = "u"
    case uprilezitosti = "u příležitosti"
    case uprostred = "uprostřed"
    
    case v = "v"
    case vcetne = "včetně"
    case ve = "ve"
    case vedle = "vedle"
    case versus = "versus"
    case vinou = "vinou"
    case visavis = "vis-à-vis"
    case vlivem = "vlivem"
    case vne = "vně"
    case vo = "vo"
    case vod = "vod"
    case vstric = "vstříc"
    case vuci = "vůči"
    case vukol = "vůkol"
    case vz = "vz"
    case vzdor = "vzdor"
    case vzhledemk = "vzhledem k"
    
    case z = "z"
    case za = "za"
    case ze = "ze"
    case zkraje = "zkraje"
    case zpod = "zpod"
    case zpoza = "zpoza"
}
